"""
Test fixtures and helpers for Route module tests.
"""
module Fixtures

using ..TestData
using OpenSourceRoutingMachine: OSRMConfig, OSRM, LatLon

# Known coordinates in Hamburg for testing
const HAMBURG_CITY_CENTER = LatLon(53.5511, 9.9937)  # Rathaus (latitude, longitude)
const HAMBURG_AIRPORT = LatLon(53.6304, 9.9882)      # Hamburg Airport (HAM)
const HAMBURG_PORT = LatLon(53.5417, 9.9667)         # Port area
const HAMBURG_ALTONA = LatLon(53.5528, 9.9352)       # Altona station

"""
    get_test_config() -> OSRMConfig

Get an OSRMConfig instance using the test data.
"""
const _OSRM_CONFIG = OSRMConfig(TestData.get_test_osrm_path())

"""
    get_test_osrm() -> OSRM

Get a test OSRM instance using the test data configuration.
"""
const _OSRM_INSTANCE = OSRM(_OSRM_CONFIG)

function get_test_osrm()
    return _OSRM_INSTANCE
end

function get_test_config()
    return _OSRM_CONFIG
end

"""
    hamburg_coordinates() -> Vector{LatLon}

Get a list of known Hamburg coordinates for testing.
"""
function hamburg_coordinates()
    return [
        HAMBURG_CITY_CENTER,
        HAMBURG_AIRPORT,
        HAMBURG_PORT,
        HAMBURG_ALTONA,
    ]
end

# Match test coordinates (generated by generate_match_test_data.jl)
# These coordinates are validated to produce successful matches
const MATCH_TEST_COORDS_CITY_CENTER_TO_AIRPORT = [
    LatLon(53.551113, 9.993674),
    LatLon(53.551086, 9.994772),
    LatLon(53.551056, 9.99587),
    LatLon(53.55103, 9.996967),
    LatLon(53.551, 9.998065),
    LatLon(53.550972, 9.999163),
    LatLon(53.55094, 10.00026),
    LatLon(53.550915, 10.001358),
    LatLon(53.550888, 10.002455),
    LatLon(53.550858, 10.003552),
    LatLon(53.55083, 10.00465),
    LatLon(53.5508, 10.005748),
    LatLon(53.550774, 10.006845),
    LatLon(53.550743, 10.007943),
    LatLon(53.550716, 10.009041),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_PORT = [
    LatLon(53.551113, 9.993674),
    LatLon(53.551086, 9.994772),
    LatLon(53.551056, 9.99587),
    LatLon(53.55103, 9.996967),
    LatLon(53.551, 9.998065),
    LatLon(53.550972, 9.999163),
    LatLon(53.55094, 10.00026),
    LatLon(53.550915, 10.001358),
    LatLon(53.550888, 10.002455),
    LatLon(53.550858, 10.003552),
    LatLon(53.55083, 10.00465),
    LatLon(53.5508, 10.005748),
    LatLon(53.550774, 10.006845),
    LatLon(53.550743, 10.007943),
    LatLon(53.550716, 10.009041),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_ALTONA = [
    LatLon(53.551113, 9.993674),
    LatLon(53.551086, 9.994772),
    LatLon(53.551056, 9.99587),
    LatLon(53.55103, 9.996967),
    LatLon(53.551, 9.998065),
    LatLon(53.550972, 9.999163),
    LatLon(53.55094, 10.00026),
    LatLon(53.550915, 10.001358),
    LatLon(53.550888, 10.002455),
    LatLon(53.550858, 10.003552),
    LatLon(53.55083, 10.00465),
    LatLon(53.5508, 10.005748),
    LatLon(53.550774, 10.006845),
    LatLon(53.550743, 10.007943),
    LatLon(53.550716, 10.009041),
]

const MATCH_TEST_COORDS_MULTI_SEGMENT = [
    LatLon(53.551113, 9.993674),
    LatLon(53.551086, 9.994772),
    LatLon(53.551056, 9.99587),
    LatLon(53.55103, 9.996967),
    LatLon(53.551, 9.998065),
    LatLon(53.550972, 9.999163),
    LatLon(53.55094, 10.00026),
    LatLon(53.550915, 10.001358),
    LatLon(53.550888, 10.002455),
    LatLon(53.550858, 10.003552),
    LatLon(53.55083, 10.00465),
    LatLon(53.5508, 10.005748),
    LatLon(53.550774, 10.006845),
    LatLon(53.550743, 10.007943),
    LatLon(53.550716, 10.009041),
]

end # module
