"""
Test fixtures and helpers for Route module tests.
"""
module Fixtures

using ..TestData
using OpenSourceRoutingMachine: OSRMConfig, OSRM, LatLon

# Known coordinates in Hamburg for testing
const HAMBURG_CITY_CENTER = LatLon(53.5511f0, 9.9937f0)  # Rathaus (latitude, longitude)
const HAMBURG_AIRPORT = LatLon(53.6304f0, 9.9882f0)      # Hamburg Airport (HAM)
const HAMBURG_PORT = LatLon(53.5417f0, 9.9667f0)         # Port area
const HAMBURG_ALTONA = LatLon(53.5528f0, 9.9352f0)       # Altona station

"""
    get_test_config() -> OSRMConfig

Get an OSRMConfig instance using the test data.
"""
const _OSRM_CONFIG = OSRMConfig(TestData.get_test_osrm_path())

"""
    get_test_osrm() -> OSRM

Get a test OSRM instance using the test data configuration.
"""
const _OSRM_INSTANCE = OSRM(_OSRM_CONFIG)

function get_test_osrm()
    return _OSRM_INSTANCE
end

function get_test_config()
    return _OSRM_CONFIG
end

"""
    hamburg_coordinates() -> Vector{LatLon}

Get a list of known Hamburg coordinates for testing.
"""
function hamburg_coordinates()
    return [
        HAMBURG_CITY_CENTER,
        HAMBURG_AIRPORT,
        HAMBURG_PORT,
        HAMBURG_ALTONA,
    ]
end

# Match test coordinates (generated by generate_match_test_data.jl)
# These coordinates are validated to produce successful matches
const MATCH_TEST_COORDS_CITY_CENTER_TO_AIRPORT = [
    LatLon(53.551113f0, 9.993674f0),
    LatLon(53.551086f0, 9.994772f0),
    LatLon(53.551056f0, 9.99587f0),
    LatLon(53.55103f0, 9.996967f0),
    LatLon(53.551f0, 9.998065f0),
    LatLon(53.550972f0, 9.999163f0),
    LatLon(53.55094f0, 10.00026f0),
    LatLon(53.550915f0, 10.001358f0),
    LatLon(53.550888f0, 10.002455f0),
    LatLon(53.550858f0, 10.003552f0),
    LatLon(53.55083f0, 10.00465f0),
    LatLon(53.5508f0, 10.005748f0),
    LatLon(53.550774f0, 10.006845f0),
    LatLon(53.550743f0, 10.007943f0),
    LatLon(53.550716f0, 10.009041f0),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_PORT = [
    LatLon(53.551113f0, 9.993674f0),
    LatLon(53.551086f0, 9.994772f0),
    LatLon(53.551056f0, 9.99587f0),
    LatLon(53.55103f0, 9.996967f0),
    LatLon(53.551f0, 9.998065f0),
    LatLon(53.550972f0, 9.999163f0),
    LatLon(53.55094f0, 10.00026f0),
    LatLon(53.550915f0, 10.001358f0),
    LatLon(53.550888f0, 10.002455f0),
    LatLon(53.550858f0, 10.003552f0),
    LatLon(53.55083f0, 10.00465f0),
    LatLon(53.5508f0, 10.005748f0),
    LatLon(53.550774f0, 10.006845f0),
    LatLon(53.550743f0, 10.007943f0),
    LatLon(53.550716f0, 10.009041f0),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_ALTONA = [
    LatLon(53.551113f0, 9.993674f0),
    LatLon(53.551086f0, 9.994772f0),
    LatLon(53.551056f0, 9.99587f0),
    LatLon(53.55103f0, 9.996967f0),
    LatLon(53.551f0, 9.998065f0),
    LatLon(53.550972f0, 9.999163f0),
    LatLon(53.55094f0, 10.00026f0),
    LatLon(53.550915f0, 10.001358f0),
    LatLon(53.550888f0, 10.002455f0),
    LatLon(53.550858f0, 10.003552f0),
    LatLon(53.55083f0, 10.00465f0),
    LatLon(53.5508f0, 10.005748f0),
    LatLon(53.550774f0, 10.006845f0),
    LatLon(53.550743f0, 10.007943f0),
    LatLon(53.550716f0, 10.009041f0),
]

const MATCH_TEST_COORDS_MULTI_SEGMENT = [
    LatLon(53.551113f0, 9.993674f0),
    LatLon(53.551086f0, 9.994772f0),
    LatLon(53.551056f0, 9.99587f0),
    LatLon(53.55103f0, 9.996967f0),
    LatLon(53.551f0, 9.998065f0),
    LatLon(53.550972f0, 9.999163f0),
    LatLon(53.55094f0, 10.00026f0),
    LatLon(53.550915f0, 10.001358f0),
    LatLon(53.550888f0, 10.002455f0),
    LatLon(53.550858f0, 10.003552f0),
    LatLon(53.55083f0, 10.00465f0),
    LatLon(53.5508f0, 10.005748f0),
    LatLon(53.550774f0, 10.006845f0),
    LatLon(53.550743f0, 10.007943f0),
    LatLon(53.550716f0, 10.009041f0),
]

end # module
