"""
Test fixtures and helpers for Route module tests.
"""
module Fixtures

using ..TestData
using OpenSourceRoutingMachine: OSRMConfig, OSRM, Position

# Known coordinates in Hamburg for testing
const HAMBURG_CITY_CENTER = Position(9.9937, 53.5511)  # Rathaus (longitude, latitude)
const HAMBURG_AIRPORT = Position(9.9882, 53.6304)      # Hamburg Airport (HAM)
const HAMBURG_PORT = Position(9.9667, 53.5417)         # Port area
const HAMBURG_ALTONA = Position(9.9352, 53.5528)       # Altona station

"""
    get_test_config() -> OSRMConfig

Get an OSRMConfig instance using the test data.
"""
const _OSRM_CONFIG = OSRMConfig(TestData.get_test_osrm_base_path())

"""
    get_test_osrm() -> OSRM

Get a test OSRM instance using the test data configuration.
"""
const _OSRM_INSTANCE = OSRM(_OSRM_CONFIG)

function get_test_osrm()
    return _OSRM_INSTANCE
end

function get_test_config()
    return _OSRM_CONFIG
end

"""
    hamburg_coordinates() -> Vector{Position}

Get a list of known Hamburg coordinates for testing.
"""
function hamburg_coordinates()
    return [
        HAMBURG_CITY_CENTER,
        HAMBURG_AIRPORT,
        HAMBURG_PORT,
        HAMBURG_ALTONA,
    ]
end

# Match test coordinates (generated by generate_match_test_data.jl)
# These coordinates are validated to produce successful matches
const MATCH_TEST_COORDS_CITY_CENTER_TO_AIRPORT = [
    Position(9.993674, 53.551113),
    Position(9.994772, 53.551086),
    Position(9.99587, 53.551056),
    Position(9.996967, 53.55103),
    Position(9.998065, 53.551),
    Position(9.999163, 53.550972),
    Position(10.00026, 53.55094),
    Position(10.001358, 53.550915),
    Position(10.002455, 53.550888),
    Position(10.003552, 53.550858),
    Position(10.00465, 53.55083),
    Position(10.005748, 53.5508),
    Position(10.006845, 53.550774),
    Position(10.007943, 53.550743),
    Position(10.009041, 53.550716),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_PORT = [
    Position(9.993674, 53.551113),
    Position(9.994772, 53.551086),
    Position(9.99587, 53.551056),
    Position(9.996967, 53.55103),
    Position(9.998065, 53.551),
    Position(9.999163, 53.550972),
    Position(10.00026, 53.55094),
    Position(10.001358, 53.550915),
    Position(10.002455, 53.550888),
    Position(10.003552, 53.550858),
    Position(10.00465, 53.55083),
    Position(10.005748, 53.5508),
    Position(10.006845, 53.550774),
    Position(10.007943, 53.550743),
    Position(10.009041, 53.550716),
]

const MATCH_TEST_COORDS_CITY_CENTER_TO_ALTONA = [
    Position(9.993674, 53.551113),
    Position(9.994772, 53.551086),
    Position(9.99587, 53.551056),
    Position(9.996967, 53.55103),
    Position(9.998065, 53.551),
    Position(9.999163, 53.550972),
    Position(10.00026, 53.55094),
    Position(10.001358, 53.550915),
    Position(10.002455, 53.550888),
    Position(10.003552, 53.550858),
    Position(10.00465, 53.55083),
    Position(10.005748, 53.5508),
    Position(10.006845, 53.550774),
    Position(10.007943, 53.550743),
    Position(10.009041, 53.550716),
]

const MATCH_TEST_COORDS_MULTI_SEGMENT = [
    Position(9.993674, 53.551113),
    Position(9.994772, 53.551086),
    Position(9.99587, 53.551056),
    Position(9.996967, 53.55103),
    Position(9.998065, 53.551),
    Position(9.999163, 53.550972),
    Position(10.00026, 53.55094),
    Position(10.001358, 53.550915),
    Position(10.002455, 53.550888),
    Position(10.003552, 53.550858),
    Position(10.00465, 53.55083),
    Position(10.005748, 53.5508),
    Position(10.006845, 53.550774),
    Position(10.007943, 53.550743),
    Position(10.009041, 53.550716),
]

end # module
