# Auto-generated Julia code from FlatBuffers schema files
# DO NOT EDIT MANUALLY - Generated by Generator.jl

using FlatBuffers
using CEnum

# Enums
@cenum(
    ManeuverType::UInt8, begin
        MANEUVER_TYPE_TURN = 0
        MANEUVER_TYPE_NEW_NAME = 1
        MANEUVER_TYPE_DEPART = 2
        MANEUVER_TYPE_ARRIVE = 3
        MANEUVER_TYPE_MERGE = 4
        MANEUVER_TYPE_ON_RAMP = 5
        MANEUVER_TYPE_OFF_RAMP = 6
        MANEUVER_TYPE_FORK = 7
        MANEUVER_TYPE_END_OF_ROAD = 8
        MANEUVER_TYPE_CONTINUE = 9
        MANEUVER_TYPE_ROUNDABOUT = 10
        MANEUVER_TYPE_ROTARY = 11
        MANEUVER_TYPE_ROUNDABOUT_TURN = 12
        MANEUVER_TYPE_NOTIFICATION = 13
        MANEUVER_TYPE_EXIT_ROUNDABOUT = 14
        MANEUVER_TYPE_EXIT_ROTARY = 15
    end
)

@cenum(
    Turn::UInt8, begin
        TURN_NONE = 0
        TURN_U_TURN = 1
        TURN_SHARP_RIGHT = 2
        TURN_RIGHT = 3
        TURN_SLIGHT_RIGHT = 4
        TURN_STRAIGHT = 5
        TURN_SLIGHT_LEFT = 6
        TURN_LEFT = 7
        TURN_SHARP_LEFT = 8
    end
)

# Structs (immutable value types)
FlatBuffers.@STRUCT struct Position
    longitude::Float32
    latitude::Float32
end

FlatBuffers.@STRUCT struct Uint64Pair
    first::UInt64
    second::UInt64
end

# Tables (mutable reference types)
FlatBuffers.@with_kw mutable struct StepManeuver
    location::Union{Position, Nothing} = nothing
    bearing_before::Union{UInt16, Nothing} = nothing
    bearing_after::Union{UInt16, Nothing} = nothing
    type::Union{ManeuverType, Nothing} = nothing
    modifier::Union{Turn, Nothing} = nothing
    exit::Union{UInt8, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Error
    code::Union{String, Nothing} = nothing
    message::Union{String, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Waypoint
    hint::Union{String, Nothing} = nothing
    distance::Union{Float32, Nothing} = nothing
    name::Union{String, Nothing} = nothing
    location::Union{Position, Nothing} = nothing
    nodes::Union{Uint64Pair, Nothing} = nothing
    matchings_index::Union{UInt32, Nothing} = nothing
    waypoint_index::Union{UInt32, Nothing} = nothing
    alternatives_count::Union{UInt32, Nothing} = nothing
    trips_index::Union{UInt32, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Lane
    indications::Vector{Turn} = []
    valid::Union{Bool, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Metadata
    datasource_names::Vector{String} = []
end

FlatBuffers.@with_kw mutable struct TableResult
    durations::Vector{Float32} = []
    rows::Union{UInt16, Nothing} = nothing
    cols::Union{UInt16, Nothing} = nothing
    distances::Vector{Float32} = []
    destinations::Vector{Waypoint} = []
    fallback_speed_cells::Vector{UInt32} = []
end

FlatBuffers.@with_kw mutable struct Intersection
    location::Union{Position, Nothing} = nothing
    bearings::Vector{Int16} = []
    classes::Vector{String} = []
    entry::Vector{Bool} = []
    in_bearing::Union{UInt32, Nothing} = nothing
    out_bearing::Union{UInt32, Nothing} = nothing
    lanes::Vector{Lane} = []
end

FlatBuffers.@with_kw mutable struct Annotation
    distance::Vector{UInt32} = []
    duration::Vector{UInt32} = []
    datasources::Vector{UInt32} = []
    nodes::Vector{UInt32} = []
    weight::Vector{UInt32} = []
    speed::Vector{Float32} = []
    metadata::Union{Metadata, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Step
    distance::Union{Float32, Nothing} = nothing
    duration::Union{Float32, Nothing} = nothing
    polyline::Union{String, Nothing} = nothing
    coordinates::Vector{Position} = []
    weight::Union{Float32, Nothing} = nothing
    name::Union{String, Nothing} = nothing
    ref::Union{String, Nothing} = nothing
    pronunciation::Union{String, Nothing} = nothing
    destinations::Union{String, Nothing} = nothing
    exits::Union{String, Nothing} = nothing
    mode::Union{String, Nothing} = nothing
    maneuver::Union{StepManeuver, Nothing} = nothing
    intersections::Vector{Intersection} = []
    rotary_name::Union{String, Nothing} = nothing
    rotary_pronunciation::Union{String, Nothing} = nothing
    driving_side::Union{Bool, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Leg
    distance::Union{Float64, Nothing} = nothing
    duration::Union{Float64, Nothing} = nothing
    weight::Union{Float64, Nothing} = nothing
    summary::Union{String, Nothing} = nothing
    annotations::Union{Annotation, Nothing} = nothing
    steps::Vector{Step} = []
end

FlatBuffers.@with_kw mutable struct RouteObject
    distance::Union{Float32, Nothing} = nothing
    duration::Union{Float32, Nothing} = nothing
    weight::Union{Float32, Nothing} = nothing
    weight_name::Union{String, Nothing} = nothing
    confidence::Union{Float32, Nothing} = nothing
    polyline::Union{String, Nothing} = nothing
    coordinates::Vector{Position} = []
    legs::Vector{Leg} = []
end

FlatBuffers.@with_kw mutable struct FBResult
    error::Bool = false
    code::Union{Error, Nothing} = nothing
    data_version::Union{String, Nothing} = nothing
    waypoints::Vector{Waypoint} = []
    routes::Vector{RouteObject} = []
    table::Union{TableResult, Nothing} = nothing
end
