# Auto-generated Julia code from FlatBuffers schema files
# DO NOT EDIT MANUALLY - Generated by Generator.jl

using FlatBuffers
using CEnum

# Enums
@cenum(
    ManeuverType::UInt8, begin
        maneuver_type_turn = 0
        maneuver_type_new_name = 1
        maneuver_type_depart = 2
        maneuver_type_arrive = 3
        maneuver_type_merge = 4
        maneuver_type_on_ramp = 5
        maneuver_type_off_ramp = 6
        maneuver_type_fork = 7
        maneuver_type_end_of_road = 8
        maneuver_type_continue = 9
        maneuver_type_roundabout = 10
        maneuver_type_rotary = 11
        maneuver_type_roundabout_turn = 12
        maneuver_type_notification = 13
        maneuver_type_exit_roundabout = 14
        maneuver_type_exit_rotary = 15
    end
)

@cenum(
    Turn::UInt8, begin
        turn_none = 0
        turn_u_turn = 1
        turn_sharp_right = 2
        turn_right = 3
        turn_slight_right = 4
        turn_straight = 5
        turn_slight_left = 6
        turn_left = 7
        turn_sharp_left = 8
    end
)

# Structs (immutable value types)
FlatBuffers.@STRUCT struct Position
    longitude::Float32
    latitude::Float32
end

FlatBuffers.@STRUCT struct Uint64Pair
    first::UInt64
    second::UInt64
end

# Tables (mutable reference types)
FlatBuffers.@with_kw mutable struct StepManeuver
    location::Union{Position, Nothing} = nothing
    bearing_before::Union{UInt16, Nothing} = nothing
    bearing_after::Union{UInt16, Nothing} = nothing
    type::Union{ManeuverType, Nothing} = nothing
    modifier::Union{Turn, Nothing} = nothing
    exit::Union{UInt8, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Error
    code::Union{String, Nothing} = nothing
    message::Union{String, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Waypoint
    hint::Union{String, Nothing} = nothing
    distance::Union{Float32, Nothing} = nothing
    name::Union{String, Nothing} = nothing
    location::Union{Position, Nothing} = nothing
    nodes::Union{Uint64Pair, Nothing} = nothing
    matchings_index::Union{UInt32, Nothing} = nothing
    waypoint_index::Union{UInt32, Nothing} = nothing
    alternatives_count::Union{UInt32, Nothing} = nothing
    trips_index::Union{UInt32, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Lane
    indications::Vector{Turn} = []
    valid::Union{Bool, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Metadata
    datasource_names::Vector{String} = []
end

FlatBuffers.@with_kw mutable struct TableResult
    durations::Vector{Float32} = []
    rows::Union{UInt16, Nothing} = nothing
    cols::Union{UInt16, Nothing} = nothing
    distances::Vector{Float32} = []
    destinations::Vector{Waypoint} = []
    fallback_speed_cells::Vector{UInt32} = []
end

FlatBuffers.@with_kw mutable struct Intersection
    location::Union{Position, Nothing} = nothing
    bearings::Vector{Int16} = []
    classes::Vector{String} = []
    entry::Vector{Bool} = []
    in_bearing::Union{UInt32, Nothing} = nothing
    out_bearing::Union{UInt32, Nothing} = nothing
    lanes::Vector{Lane} = []
end

FlatBuffers.@with_kw mutable struct Annotation
    distance::Vector{UInt32} = []
    duration::Vector{UInt32} = []
    datasources::Vector{UInt32} = []
    nodes::Vector{UInt32} = []
    weight::Vector{UInt32} = []
    speed::Vector{Float32} = []
    metadata::Union{Metadata, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Step
    distance::Union{Float32, Nothing} = nothing
    duration::Union{Float32, Nothing} = nothing
    polyline::Union{String, Nothing} = nothing
    coordinates::Vector{Position} = []
    weight::Union{Float32, Nothing} = nothing
    name::Union{String, Nothing} = nothing
    ref::Union{String, Nothing} = nothing
    pronunciation::Union{String, Nothing} = nothing
    destinations::Union{String, Nothing} = nothing
    exits::Union{String, Nothing} = nothing
    mode::Union{String, Nothing} = nothing
    maneuver::Union{StepManeuver, Nothing} = nothing
    intersections::Vector{Intersection} = []
    rotary_name::Union{String, Nothing} = nothing
    rotary_pronunciation::Union{String, Nothing} = nothing
    driving_side::Union{Bool, Nothing} = nothing
end

FlatBuffers.@with_kw mutable struct Leg
    distance::Union{Float64, Nothing} = nothing
    duration::Union{Float64, Nothing} = nothing
    weight::Union{Float64, Nothing} = nothing
    summary::Union{String, Nothing} = nothing
    annotations::Union{Annotation, Nothing} = nothing
    steps::Vector{Step} = []
end

FlatBuffers.@with_kw mutable struct RouteObject
    distance::Union{Float32, Nothing} = nothing
    duration::Union{Float32, Nothing} = nothing
    weight::Union{Float32, Nothing} = nothing
    weight_name::Union{String, Nothing} = nothing
    confidence::Union{Float32, Nothing} = nothing
    polyline::Union{String, Nothing} = nothing
    coordinates::Vector{Position} = []
    legs::Vector{Leg} = []
end

FlatBuffers.@with_kw mutable struct FBResult
    error::Bool = false
    code::Union{Error, Nothing} = nothing
    data_version::Union{String, Nothing} = nothing
    waypoints::Vector{Waypoint} = []
    routes::Vector{RouteObject} = []
    table::Union{TableResult, Nothing} = nothing
end
